const categories = {
    "First Date": ["romantic restaurant", "luxury dining", "michelin star", "fine dining", "cozy café", "wine bars"],
    "Guys Night": ["sports bar", "arcade", "casual bar", "brewery", "grill and pub", "beerbar"],
    "Girls Night": ["cocktail bars", "wine bars", "lounges", "trendy cafés", "dessert bars"],
    "Anniversary": ["fine dining", "romantic restaurant", "luxury dining", "michelin star", "intimate bistro"],
    "Birthday": ["fun restaurant", "family-friendly", "arcade", "themed dining", "karaoke bars"],
    "Romantic Getaway": ["secluded restaurants", "michelin star", "romantic restaurant", "wine and dine"],
    "Weekend Getaway": ["country-style dining", "farm-to-table", "rustic restaurants", "vineyard dining"],
    "Summer Fling": ["outdoor dining", "beachside restaurants", "tropical cocktails", "seafood shacks"],
    "Quick Getaway": ["casual cafés", "fast-casual dining", "pop-up restaurants", "food trucks"],
    "Solo": ["cozy café", "coffee house", "reading-friendly spots", "quiet dining"],
    "Family Dinner": ["family-style restaurants", "buffets", "casual dining", "pizza places"],
    "Business Lunch": ["bistros", "cafés", "steakhouses", "sushi bars"],
    "Brunch with Friends": ["brunch cafés", "pancake houses", "bakeries", "brunch buffets"],
    "Date Night": ["romantic bistros", "wine bars", "cozy restaurants", "fine dining"],
    "Celebration Dinner": ["steakhouses", "seafood restaurants", "luxury dining", "banquet halls"],
    "Casual Dining": ["diners", "cafés", "grill and bar", "family-friendly restaurants"],
    "Fine Dining": ["michelin star", "luxury dining", "exclusive restaurants", "chef-led dining"],
    "Happy Hour": ["cocktail bars", "pubs", "wine bars", "brewery"],
    "Food Tasting": ["tasting menus", "wine and dine", "chef's table", "food festivals"],
    "Chef's Special": ["chef-led dining", "exclusive menus", "seasonal dishes", "gourmet restaurants"],
    "Wine Pairing": ["wine bars", "vineyards", "fine dining", "tasting menus"],
    "Dessert Night": ["dessert bars", "ice cream parlors", "bakeries", "chocolate shops"],
    "Vegan Feast": ["vegan restaurants", "plant-based cafés", "organic dining", "farm-to-table"],
    "Seafood Delight": ["seafood restaurants", "fish markets", "oyster bars", "beachside dining"],
    "Steak Night": ["steakhouses", "grill and bar", "luxury dining", "American cuisine"],
    "Ethnic Cuisine Adventure": ["ethnic restaurants", "fusion cuisine", "street food", "cultural dining"],
    "Farm-to-Table Experience": ["farm-to-table restaurants", "organic dining", "seasonal menus", "rustic dining"],
    "Seasonal Menu": ["seasonal restaurants", "farm-to-table", "chef's special", "gourmet dining"],
    "Pop-Up Event": ["pop-up restaurants", "food trucks", "temporary dining", "exclusive events"],
    "Cooking Class": ["cooking schools", "interactive dining", "chef-led classes", "culinary workshops"],
    "Adventure": ["themed dining", "unusual cuisine", "live performance restaurants", "street food"],
    "Wine Wedding Resort": ["wine bars", "vineyards", "luxury dining", "romantic restaurants", "banquet-style dining"],
    "Fast Food": ["burger joints", "fried chicken spots", "pizza chains", "drive-thru restaurants"],
    "Dive Bar": ["hole-in-the-wall bars", "local pubs", "karaoke dive bars", "grungy hangouts"],
    "Sports Bar": ["TV-equipped bars", "pubs with games", "grill and bar", "beer bars"],
    "Michelin Star Restaurant": ["award-winning dining", "chef-led dining", "luxury cuisine", "exclusive restaurants"],
    "Luxury Restaurant": ["fine dining", "high-end dining", "luxury cuisine", "exclusive private rooms"],
    "Standard Restaurant": ["casual dining", "family-style restaurants", "local favorites"],
    "Lounge": ["trendy lounges", "cocktail lounges", "relaxed atmosphere"],
    "American": ["barbecue spots", "diners", "grill and bar", "fast-casual American food"],
    "Tex-Mex": ["taco joints", "burrito spots", "Tex-Mex grills"],
    "Asian": ["sushi spots", "ramen bars", "Asian fusion"],
    "Chinese": ["dim sum restaurants", "Szechuan cuisine", "noodle houses"],
    "Japanese": ["sushi bars", "ramen spots", "teppanyaki grills"],
    "Korean": ["KBBQ", "kimchi spots", "soju bars"],
    "Thai": ["curries", "Pad Thai", "street Thai food"],
    "Vietnamese": ["pho houses", "banh mi cafes", "Vietnamese noodle spots"],
    "Indian": ["tandoori houses", "Indian curries", "vegetarian Indian food"],
    "European": ["Italian trattorias", "French bistros", "Spanish tapas bars", "British pubs"],
    "Middle Eastern": ["shawarma spots", "hummus bars", "Lebanese cuisine"],
    "Latin American": ["taco trucks", "Brazilian steakhouses", "Cuban cafes"],
    "African": ["Ethiopian spots", "Moroccan tagines", "South African grills"],
    "Caribbean": ["jerk chicken shacks", "beachside Caribbean spots"],
    "Brunch": ["brunch cafés", "all-day breakfast spots", "eggs benedict specialists"],
    "Dessert": ["ice cream parlors", "dessert bars", "bakeries"],
    "Bakery": ["artisanal bread shops", "pastry cafés", "dessert bakeries"],
    "Café": ["coffee houses", "tea rooms", "hipster cafés"],
    "Vegetarian/Vegan": ["plant-based restaurants", "vegan-friendly spots", "organic eateries"],
    "Halal/Kosher": ["halal grills", "kosher delis", "Middle Eastern halal"],
    "Organic": ["farm-to-table", "healthy eating", "organic specialty spots"],
    "Delivery-only restaurants": ["ghost kitchens", "cloud kitchens", "delivery-focused spots"],
    "Pop-Up Restaurants": ["experimental dining", "seasonal pop-ups", "event-based restaurants"],
    "Food Trucks": ["taco trucks", "burger trucks", "street food"],
    "Street Food": ["food stalls", "local street vendors"],
    "Healthy Eating": ["salad bars", "smoothie spots", "nutritional cafés"],
    "Wine Bars": ["wine tasting spots", "vineyards with dining", "casual wine bars"],
    "Craft Beer Bars": ["microbreweries", "beer gardens"],
    "Cocktail Bars": ["mixology spots", "rooftop bars"],
    "Tea Houses": ["tea lounges", "bubble tea shops"],
    "Pet-Friendly": ["dog cafés", "outdoor pet-friendly dining"],
    "Senior-Friendly": ["quiet dining", "accessible restaurants"],
    "Child-Friendly": ["kid-friendly menus", "play areas"],
};

const matchCategories = (experience) => categories[experience] || [];

module.exports = { matchCategories };
